package testkit

import (
	"archive/zip"
	"bytes"
	"compress/flate"
	"encoding/binary"
	"fmt"
	"hash/crc32"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// DOSEpoch is the fixed timestamp synthetic archives carry, so generated bytes
// stay reproducible.
var DOSEpoch = time.Date(1980, 1, 1, 0, 0, 0, 0, time.UTC)

// Entry is one member of a synthetic archive.
type Entry struct {
	Name   string
	Data   []byte
	Method uint16 // zip.Store or zip.Deflate; Store when zero and Data is nil
	Dir    bool
}

// Archive describes a synthetic .procreate file.
type Archive struct {
	// Entries are written in this order, because archive order is part of what
	// the slimming contract preserves.
	Entries []Entry

	// ProcreateStyle writes entries the way Procreate does: sizes and CRC in the
	// local header, general-purpose flags 0x0006, and no data descriptor.
	//
	// Go's zip.Writer always sets the data-descriptor flag, so an archive built
	// the ordinary way cannot reproduce the shape of a real project - and a
	// rewriter that corrupts its reader by handing a *zip.File's header to
	// CreateHeader looks perfectly healthy against such an archive while failing
	// every real file. This flag exists so tests can tell the difference.
	ProcreateStyle bool
}

// procreateFlags are the general-purpose bits Procreate sets: the two deflate
// level hints, and notably not bit 3, which would announce a data descriptor.
const procreateFlags = 0x0006

// Bytes renders the archive.
func (a Archive) Bytes() []byte {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, e := range a.Entries {
		if err := a.writeEntry(zw, e); err != nil {
			panic(err)
		}
	}
	if err := zw.Close(); err != nil {
		panic(err)
	}
	return buf.Bytes()
}

func (a Archive) writeEntry(zw *zip.Writer, e Entry) error {
	name := e.Name
	if e.Dir && name != "" && name[len(name)-1] != '/' {
		name += "/"
	}
	method := e.Method
	if e.Dir {
		method = zip.Store
	}
	if !a.ProcreateStyle {
		w, err := zw.CreateHeader(&zip.FileHeader{Name: name, Method: method, Modified: DOSEpoch})
		if err != nil {
			return err
		}
		if e.Dir {
			return nil
		}
		_, err = w.Write(e.Data)
		return err
	}

	payload := e.Data
	if method == zip.Deflate {
		var c bytes.Buffer
		fw, err := flate.NewWriter(&c, flate.DefaultCompression)
		if err != nil {
			return err
		}
		if _, err := fw.Write(e.Data); err != nil {
			return err
		}
		if err := fw.Close(); err != nil {
			return err
		}
		payload = c.Bytes()
	}
	hdr := &zip.FileHeader{
		Name:               name,
		Method:             method,
		Modified:           DOSEpoch,
		Flags:              procreateFlags,
		CRC32:              crc32.ChecksumIEEE(e.Data),
		CompressedSize64:   uint64(len(payload)),
		UncompressedSize64: uint64(len(e.Data)),
	}
	w, err := zw.CreateRaw(hdr)
	if err != nil {
		return err
	}
	if e.Dir {
		return nil
	}
	_, err = w.Write(payload)
	return err
}

// Write writes the archive under dir and returns its path.
func (a Archive) Write(t *testing.T, dir, name string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(p, a.Bytes(), 0o644); err != nil {
		t.Fatalf("write %s: %v", p, err)
	}
	return p
}

// Canvas geometry of the synthetic project. The two edges differ and neither is
// a whole number of tiles, so the grid is 2 columns by 3 rows with clipped right
// and bottom tiles. A square canvas would hide both a transposed grid and a
// wrong clip, which is exactly what the reader has to get right.
const (
	CanvasW = 100
	CanvasH = 140
)

// Project builds a realistic project: the members every Procreate document has,
// a full grid of layer tiles, and n timelapse segments. Entry order deliberately
// interleaves the timelapse with everything else, the way real archives do.
func Project(n int) Archive {
	a := Archive{ProcreateStyle: true}
	add := func(name string, data []byte, method uint16) {
		a.Entries = append(a.Entries, Entry{Name: name, Data: data, Method: method})
	}
	ink := color.NRGBA{R: 0x20, G: 0x40, B: 0x60, A: 0xff}
	translucent := color.NRGBA{R: 0xc0, G: 0x10, B: 0x30, A: 0x80}

	add(tileName(layerUUID, 0, 0), tileAt(0, 0, ink), zip.Deflate)
	add("Document.archive", DocumentArchive(CanvasW, CanvasH), zip.Deflate)
	for i := 1; i <= n; i++ {
		add(fmt.Sprintf("video/segments/segment-%d.mp4", i), segForTest(i), zip.Deflate)
		if i == 1 {
			add("QuickLook/Thumbnail.png", ThumbnailPNG(32, 32), zip.Deflate)
		}
	}
	// The rest of the layer's grid, with the bottom row left translucent, plus
	// the flattened composite Procreate keeps for previews. The last column and
	// last row are the clipped edges.
	for row := 0; row < GridRows; row++ {
		for col := 0; col < GridCols; col++ {
			if row == 0 && col == 0 {
				continue
			}
			c := ink
			if row == GridRows-1 {
				c = translucent
			}
			add(tileName(layerUUID, col, row), tileAt(col, row, c), zip.Deflate)
		}
	}
	for row := 0; row < GridRows; row++ {
		for col := 0; col < GridCols; col++ {
			add(tileName(compositeUUID, col, row), tileAt(col, row, ink), zip.Deflate)
		}
	}
	// A zero-length placeholder for the recording Procreate would append next.
	// It lives under video/ but is not a segment, so slimming must keep it.
	add("video/active-0.mp4", nil, zip.Deflate)
	return a
}

// Grid dimensions of the synthetic canvas.
const (
	GridCols = (CanvasW + TileSize - 1) / TileSize
	GridRows = (CanvasH + TileSize - 1) / TileSize
)

// tileName renders a tile member name. Procreate orders the indices row~column,
// so synthetic archives have to do the same or they would not exercise the
// reader's mapping at all.
func tileName(uuid string, col, row int) string {
	return fmt.Sprintf("%s/%d~%d.lz4", uuid, row, col)
}

// tileAt builds the tile at column/row of the synthetic canvas, clipped to the
// canvas the way Procreate stores edge tiles.
func tileAt(col, row int, c color.NRGBA) []byte {
	w := min(TileSize, CanvasW-col*TileSize)
	h := min(TileSize, CanvasH-row*TileSize)
	if w <= 0 || h <= 0 {
		return AppleLZ4Stored(nil)
	}
	return StoredTile(w, h, c)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

const layerUUID = "A92B96ED-4128-484D-9016-7718D274B467"

// LayerUUID is the UUID Project and DocumentArchive agree on for their layer.
func LayerUUID() string { return layerUUID }

func segForTest(n int) []byte {
	return Segment(320, 240, []uint32{1000 + uint32(n)*7, 900 + uint32(n)*3}, []uint32{700 + uint32(n)*5})
}

// ThumbnailPNG renders a deterministic PNG, standing in for
// QuickLook/Thumbnail.png.
func ThumbnailPNG(w, h int) []byte {
	img := image.NewNRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			img.SetNRGBA(x, y, color.NRGBA{R: uint8(x * 4), G: uint8(y * 4), B: 0x80, A: 0xff})
		}
	}
	var b bytes.Buffer
	if err := png.Encode(&b, img); err != nil {
		panic(err)
	}
	return b.Bytes()
}

// StoredTile builds a layer tile in Apple's LZ4 container using only its stored
// block form (bv4-), which needs no compressor and decodes through exactly the
// same path as a compressed one.
//
// Pixels are premultiplied RGBA laid out column by column, which is how
// Procreate stores them.
func StoredTile(w, h int, c color.NRGBA) []byte {
	px := make([]byte, 0, w*h*4)
	for x := 0; x < w; x++ {
		for y := 0; y < h; y++ {
			px = append(px, mul(c.R, c.A), mul(c.G, c.A), mul(c.B, c.A), c.A)
		}
	}
	return AppleLZ4Stored(px)
}

// StoredTileFunc is StoredTile with a per-pixel colour, for fixtures that need
// to tell one position in a tile from another.
func StoredTileFunc(w, h int, at func(x, y int) color.NRGBA) []byte {
	px := make([]byte, 0, w*h*4)
	for x := 0; x < w; x++ {
		for y := 0; y < h; y++ {
			c := at(x, y)
			px = append(px, mul(c.R, c.A), mul(c.G, c.A), mul(c.B, c.A), c.A)
		}
	}
	return AppleLZ4Stored(px)
}

func mul(v, a uint8) uint8 { return uint8((int(v)*int(a) + 127) / 255) }

// AppleLZ4Stored wraps payload in a single stored Apple LZ4 block.
func AppleLZ4Stored(payload []byte) []byte {
	out := append([]byte{}, "bv4-"...)
	out = binary.LittleEndian.AppendUint32(out, uint32(len(payload)))
	out = append(out, payload...)
	return append(out, "bv4$"...)
}
